### ISSUE TITLE
Old version nv.d3.min.js in Prestashop 8

### ISSUE THREAD

**Issue by covox76** [PrestaShop/dashgoals#47]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](./issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The issue concerns an older version of nv.d3.min.js. Updating the module in Prestashop 8.2 to the latest version 2.0.5 causes an error in the modified source code of the dashgoals.js file

### Steps to reproduce

Go to the dashboard in the back office, and the chart will not be displayed

### Expected behavior

Correct display of the chart ;-)
Update the admin\themes\default\js\vendor\nv.d3.min.js file to the latest varsion (in Prestashop 9 everything is OK)

### Actual Result

The error occurs on line 80:        chart.tooltip.contentGenerator

### PrestaShop version where the bug happens

8.2.4

### Module version where the bug happens

2.0.5

### PHP version(s) where the bug happened

8.1.34

**Comment by SharakPL** [comment]
I can confirm it doesn't work on 8.2.x shops

> Uncaught TypeError: chart.tooltip.contentGenerator is not a function
